### PR TITLE
Companion bill popup

### PR DESCRIPTION
**Pull request by ObaltzerS**
implemented companion bill popup, shows info of companion bill in similar format to the cards. Also handles not linking when companion bills are either "N/A" or "no companion bill provided". Unsure or whether the popup should include the download button, but I kept It for consistency. I also changed the language of the cards and code to match the google sheet and refer to "companion bill" rather than "companion bills" because there aren't any bills with multiple companion bills.

### CODE REVIEW

**Comment by ProfJanetDavis** [comment]
Thanks, @ObaltzerS! It looks good in the web browser, but I don't like duplicating the entire card template. That's a lot of extra code to maintain. See the [DRY Principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

[This source](https://odetocode.com/blogs/scott/archive/2016/03/21/reusing-javascript-template-literals.aspx) suggests making JavaScript template strings reusable by putting each template string in a wrapper function with appropriate parameters. Would it make sense to put the card template in a function with the listjs item as a parameter?

**Comment by ObaltzerS** [comment]
certainly, I'll give that a try.

**Comment by ObaltzerS** [comment]
Remade the cards and the companion bill as a general template, however I noticed that defining templates with an anonymous function wrapper tends to not play well with list.js. The function template() is my solution to this.

**Comment by ProfJanetDavis** [comment]
So I'm going to go ahead and merge this, but I have a question: How hard would it be to not display the Companion Bill accordion at all if there is no companion bill?

**Comment by ObaltzerS** [comment]
quite easy, however I think it might be useful information to include that bills have no companion bill

**Pull request merged**
